image: maxking/mailman-ci-runner


py35-django-1.11:
  stage: test
  script:
  - tox -e py35-django111

py36-django-1.11:
  stage: test
  script:
  - tox -e py36-django111

py36-django-20:
  stage: test
  script:
    - tox -e py36-django20

py35-django-20:
  stage: test
  script:
    - tox -e py35-django20    

coverage:
  stage: test
  script:
  - tox -e coverage
  artifacts:
    paths:
    - coverage
    expire_in: 5 days

pep8:
  stage: test
  script:
  - tox -e pep8

django-1.11-git:
  stage: test
  script:
  - tox -e py36-head

django-latest:
  stage: test
  allow_failure: true
  script:
    - tox -e py36-django-latest

pages:
  stage: deploy
  dependencies:
  - coverage
  script:
  - mv coverage/ public/
  artifacts:
    paths:
    - public
    expire_in: 5 days
  only:
  - master
